/*
 * Tank Measurement API
 *
 * API for config.json in tank_measurement
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class UsersList : IEquatable<UsersList>
    {
        /// <summary>
        /// Gets or Sets ObjectsList
        /// </summary>
        [DataMember(Name="objectsList", EmitDefaultValue=false)]
        public Object ObjectsList { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UsersList {\n");
            sb.Append("  ObjectsList: ").Append(ObjectsList).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((UsersList)obj);
        }

        /// <summary>
        /// Returns true if UsersList instances are equal
        /// </summary>
        /// <param name="other">Instance of UsersList to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UsersList other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ObjectsList == other.ObjectsList ||
                    ObjectsList != null &&
                    ObjectsList.Equals(other.ObjectsList)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ObjectsList != null)
                    hashCode = hashCode * 59 + ObjectsList.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(UsersList left, UsersList right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(UsersList left, UsersList right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
